import {
  Categories,
  CreateCategory,
  CreateOrder,
  CreateProduct,
  CreateReview,
  CreateUser,
  EditCategory,
  EditOrder,
  EditProduct,
  EditReview,
  EditUser,
  HelpDesk,
  Landing,
  LandingV2,
  Login,
  Notifications,
  Orders,
  Products,
  Profile,
  Register,
  Reviews,
  Users,
} from "../pages";
const ROUTES_CONFIG = [
  { path: "/login", element: <Login /> },
  { path: "/signup", element: <Register /> },
  { index: true, element: <Landing /> },
  { path: "/landing-v2", element: <LandingV2 /> },
  { path: "/products", element: <Products /> },
  { path: "/products/create-product", element: <CreateProduct /> },
  { path: "/products/:id", element: <EditProduct /> },
  { path: "/categories", element: <Categories /> },
  { path: "/categories/create-category", element: <CreateCategory /> },
  { path: "/categories/:id", element: <EditCategory /> },
  { path: "/orders", element: <Orders /> },
  { path: "/orders/create-order", element: <CreateOrder /> },
  { path: "/orders/1", element: <EditOrder /> },
  { path: "/reviews", element: <Reviews /> },
  { path: "/reviews/:id", element: <EditReview /> },
  { path: "/reviews/create-review", element: <CreateReview /> },
  { path: "/users", element: <Users /> },
  { path: "/users/:id", element: <EditUser /> },
  { path: "/users/create-user", element: <CreateUser /> },
  { path: "/help-desk", element: <HelpDesk /> },
  { path: "/notifications", element: <Notifications /> },
  { path: "/profile", element: <Profile /> },
];

export default ROUTES_CONFIG;
