import { SORT_ATTRIBUTES, SORT_ORDERS } from "src/types/common.types"

const PAGINATION_LIMIT: number = 10
const PAGINATION_DEFAULT_PAGE: number = 1
const SORT_ATTRIBUTE: SORT_ATTRIBUTES = SORT_ATTRIBUTES.NAME
const SORT_ORDER: SORT_ORDERS = SORT_ORDERS.DESC

// #### EXPORTS ####
export {
    PAGINATION_LIMIT,
    PAGINATION_DEFAULT_PAGE,
    SORT_ATTRIBUTE,
    SORT_ORDER
};
